site_name: MINKE Sensors Documentation
site_description: MINKE Documentation
site_author: Fab Lab Barcelona
site_url: https://participatory-tech.docs.minke.eu/
repo_name: smartcitizen-minke-docs
repo_url: https://github.com/fablabbcn/smartcitizen-minke-docs

nav:
  - Main:
    - Welcome!: index.md
    - Sensors:
      - Index: Units/index.md
      - Citizen Kit: Units/Citizen Kit.md
      - Citizen Water Kit: Units/Citizen Water Kit.md
      - Citizen Water Station: Units/Citizen Water Station.md
    - Data:
      - Sensor Platform: Data/Sensor Platform.md
      - Data Analysis: Data/Data Analysis.md
    - FAQ: _FAQ.md
    - Troubleshooting: Troubleshooting.md
  - Guides:
    - Main: Guides/index.md
    - Getting started:
      - Onboarding Sensors: Guides/getting started/Onboarding Sensors.md
      - Downloading platform data: Guides/getting started/Downloading the Data.md
      - Uploading SD-card data: Guides/getting started/Uploading SD Card Data.md
      - Updating the Wi-Fi: Guides/getting started/Updating the Wi-Fi.md
      - Using the Shell: Guides/getting started/Using the Shell.md
      - Getting firmware information: Guides/getting started/Getting firmware information.md
      - Debugging your sensors: Guides/getting started/Debugging your sensors.md
    - Calibration:
      - Water sensors: Guides/calibration/Water sensors.md
    # - Deploying sensors:
    #   - Citizen Kit: Guides/deployments/Citizen Kit.md
    #   - Citizen Water Station: Guides/deployments/Citizen Water Station.md
    #   - Power Supply: Guides/deployments/Using the power supply.md
    # - Enclosures:
    #   - Making your own enclosures: Guides/enclosures/Making your own enclosures.md
  - Webinars:
    - Webinars: Webinars/index.md
  - About:
    - About: About/about.md

theme:
  name: 'material'
  features:
    - instant
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
    - content.action.edit
    - content.action.view
    - toc.follow
    - navigation.footer
  custom_dir: 'custom_theme'
  logo: 'assets/images/MINKE-logo-small.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true
  icon:
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/MinkeProject'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/minke-project/'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCW4nzxDEUk7NRpKMAghoSDg'
    - icon: fontawesome/brands/slideshare
      link: 'https://www.slideshare.net/MinkeProject'
  project: 'Smart Citizen as part of the MINKE project has received funding from the European Community’s H2020 Programme under Grant Agreement No. 101008724.'
  footer_logo: '/assets/images/eu-flag.png'
  license: 'GNU Free Documenstation License (Version 1.3, 3 November 2008)'
  license_link: 'https://www.gnu.org/licenses/fdl-1.3-standalone.html'
  discourse: 'https://forum.smartcitizen.me/'
  disqus: 'fake'
  fullscreen_button: true
  tmp_dir: '/tmp'
  base_dir: 'docs'
  site_dir: 'site'
  local: false
  urls:
    buy:
      name: seeedstudio.com
      link: https://www.seeedstudio.com/Smart-Citizen2-3-p-6327.html
    installation:
      name: start.smartcitizen.me
      link: https://start.smartcitizen.me/
    main:
      name: smartcitizen.me
      link: https://smartcitizen.me/
    platform:
      name: smartcitizen.me/kits
      link: https://smartcitizen.me/kits
    api:
      name: api.smartcitizen.me
      link: https://api.smartcitizen.me
    ghapi:
      name: fablabbcn/smartcitizen-api
      link: https://github.com/fablabbcn/smartcitizen-api
    developer:
      name: developer.smartcitizen.me
      link: https://developer.smartcitizen.me
    forum:
      name: forum.smartcitizen.me
      link: https://forum.smartcitizen.me
    support:
      name: support@smartcitizen.me
      link: mailto:support@smartcitizen.me
    info:
      name: info@smartcitizen.me
      link: mailto:info@smartcitizen.me
    status:
      name: status.smartcitizen.me
      link: https://status.smartcitizen.me
    firmware:
      name: fablabbcn/smartcitizen-kit-2x
      link: https://github.com/fablabbcn/smartcitizen-kit-2x
    ghfablab:
      name: github.com/fablabbcn/
      link: https://github.com/search?q=org%3Afablabbcn+smartcitizen&type=repositories
    ghhardware:
      name: fablabbcn/smartcitizen-kit-2x/hardware
      link: https://github.com/fablabbcn/smartcitizen-kit-2x/tree/master/hardware
    enclosures:
      name: enclosures.smartcitizen.me
      link: https://enclosures.smartcitizen.me
    fablabbcn:
      name: Fab Lab Barcelona
      link: https://fablabbcn.org
    iaac:
      name: Institute For Advanced Architecture Of Catalonia
      link: https://iaac.net
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: Español
  #     link: /es/
  #     lang: es

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.snippets:
  #     base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

plugins:
  - search
  - macros

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
  - 'javascripts/extra.js'
